WIDTH, HEIGHT = 600, 800
FPS = 60

INITIAL_OBSTACLE_SPEED = 220.0
OBSTACLE_SPEED_INCREASE = 8.0
TIME_SCORE_RATE = 12.0
SPEED_SCORE_FACTOR = 0.08
BASE_OBSTACLE_SPAWN_INTERVAL = 1
MIN_OBSTACLE_SPAWN_INTERVAL = 0.5
OBSTACLE_COLOR = (220, 70, 70)
PLAYER_Y = int(HEIGHT * 0.82)
MAX_ACTIVE_OBSTACLES = 6
MIN_LANE_VERTICAL_GAP = HEIGHT * 0.16
MAX_DELTA_TIME = 1.0 / 30.0
POSE_UPDATE_INTERVAL = 1.0 / 8.0
ENABLE_POSE_INPUT = False
POSE_INFERENCE_WIDTH = 256
POSE_CONFIDENCE = 0.35
POSE_IOU = 0.45
POSE_MAX_DETECTIONS = 1
SPEED_MULTIPLIER_AT_HORIZON = 0.70
SPEED_MULTIPLIER_AT_BOTTOM = 1.35

COOP_SYNC_WINDOW = 0.18
COOP_JUMP_DURATION = 0.55
COOP_JUMP_HEIGHT = int(HEIGHT * 0.16)
COOP_JUMP_COLLISION_GRACE = 0.15
COOP_COLLISION_ZONE_HEIGHT = max(10, int(HEIGHT * 0.02))
COOP_AIRBORNE_DEADZONE_HEIGHT = int(COOP_JUMP_HEIGHT * 0.35)
COOP_SPAWN_INTERVAL_MIN = 1.1
COOP_SPAWN_INTERVAL_MAX = 1.9
COOP_SPEED_MULTIPLIER = 1.25

SINGLE_JUMP_DURATION = 0.30
SINGLE_JUMP_HEIGHT = int(HEIGHT * 0.10)
SINGLE_JUMP_COOLDOWN = 0.02

LANE_OFFSET_BOTTOM = int(WIDTH * 0.25)
LANES = [
    int(WIDTH / 2 - LANE_OFFSET_BOTTOM),
    int(WIDTH / 2 + LANE_OFFSET_BOTTOM),
]
HORIZON_Y = int(HEIGHT * 0.18)
LANE_GAP_TOP = int(WIDTH * 0.03)
LANE_WIDTH_BOTTOM = int(WIDTH * 0.18)
LANE_WIDTH_TOP = int(WIDTH * 0.05)
